name: '${name}'
version: '${version}'
main: '${main}'
depend:
  - PlaceholderAPI
folia-supported: true

commands:
  justteams:
    description: Main command for JustTags
    permission: justteams.command.justteams
    aliases: [jteams, jtm, teams]